spring:
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_db
    username: xa3uk
    password: perilrulit1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    doc-expansion: list
  cache:
    disabled: false
  show-actuator: false







